database:
  # Remove mysql section
  mysql:
    dsn: "root:123qwe@tcp(127.0.0.1:3306)/gochat?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

server:
  port: 8080

tencentcloud:
  app_id: 1
  secret_id: a